-- AlterTable
ALTER TABLE "Business" ADD COLUMN "taxRate" DECIMAL(5,4) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Sale" ADD COLUMN "tax" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Sale" ADD COLUMN "notes" TEXT;
ALTER TABLE "Sale" ADD COLUMN "paidAmount" DECIMAL(10,2);
ALTER TABLE "Sale" ADD COLUMN "change" DECIMAL(10,2);
